server:
  port: 8882

spring:
  application:
    name: gassman-order-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./data/gassman
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:

  rabbitmq :
    addresses: amqp://***
  cloud:
    stream:
      bindings:
        userRegistrationChannel:
          destination: gassman-user-registration
        userOrderChannel:
          destination: gassman-order-registration
        orderPaymentChannel:
          destination: gassman-order-payment
        orderPaymentConfirmationChannel:
          destination: gassman-order-payment-confirmation
        orderNonPaidReminderChannel:
          destination: gassman-order-non-paid-reminder
        orderProductDeliveryReminderChannel:
          destination: gassman-order-product-delivery-reminder
        productUpdateChannel:
          destination: gassman-product-update

job:
  orderNonPaidReminderTimeout: 2880
  orderProductDeliveryReminderTimeout: 1440
  delay: 60000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka