server:
  port: 8882

spring:
  application:
    name: gassman-order-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/gassman
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:

  rabbitmq :
    addresses: 
  cloud:
    stream:
      bindings:
        userRegistrationChannel:
          destination: gassman-user-registration
        userOrderChannel:
          destination: gassman-order-registration
        orderPaymentChannel:
          destination: gassman-order-payment

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka